### ISSUE TITLE
Encounter page

### ISSUE THREAD

**Issue by ninasander** [ninasander/capstone-project#1]
## Value Statement
As a Game Master
I need to see a list of all creatures (enemies and players) in my encounter
so that I can keep an eye on the enemy's HP (Hit points) and AC (Armor class), as well as the player's AC

## Description (Text, Scribble, Wireframe, Design)
<img width="269" alt="Bildschirmfoto 2020-08-29 um 18 34 46" src="https://user-images.githubusercontent.com/67911826/91641678-5e4d4300-ea26-11ea-95b4-fa38cf5c8743.png">

## Acceptance criteria
- [x] Enemy entries display max. HP and AC
- [x] Player entries display AC 

## Tasks
- [x] Create feature branch
- [x] Create EncounterPage component in Storybook
- [x] Create EnemyEntry component in Storybook
- [x] Create PlayerEntry component in Storybook
- [x] Write component tests
- [x] Add components to app
- [x] Add missing styles

## Complexity
low
