### ISSUE TITLE
Turn Tracker

### ISSUE THREAD

**Issue by ninasander** [ninasander/capstone-project#11]
## Value statement
As a Game Master
I need a visual highlight of the creature currently taking their turn and a button to navigate from turn to turn
so that I can easily keep track of whose turn in the combat order it is and how many rounds have been played

## Description (Text, Scribble, Wireframe, Design)
<img width="536" alt="Bildschirmfoto 2020-09-08 um 17 49 46" src="https://user-images.githubusercontent.com/67911826/92615177-1f887a00-f2bd-11ea-8890-f66a148b3084.png">

## Acceptance criteria
- [x] Active creature is visibly highlighted
- [x] At the beginning of the encounter the creature at the top of the list is highlighted
- [x] Clicking the right arrow button highlights the next creature in the order
- [x] Clicking the left arrow button goes one step back in the turn order
- [x] The left arrow is disabled at the beginning of the first turn in the first round
- [x] Clicking the right arrow button when the last creature in the order is highlighted finishes a round and highlights the first creature in the combat order again

## Tasks
- [x] Create feature branch
- [x] Add TurnButton component in storybook
- [x] Update EncounterPage component in storybook
- [x] Add components to app
- [x] Write component tests
- [x] Write integration tests with cypress
- [x] Add missing styles

## Size
small
