### ISSUE TITLE
Create page

### ISSUE THREAD

**Issue by ninasander** [ninasander/capstone-project#2]
## Value statement
As a Game Master
I need a page to enter and submit the stats for all creatures in my encounter
so that they can be correctly displayed on the encounter page

## Description (Text, Scribble, Wireframe, Design)
<img width="552" alt="Bildschirmfoto 2020-09-08 um 10 56 59" src="https://user-images.githubusercontent.com/67911826/92455523-0f3fa480-f1c2-11ea-90db-a08e3888e344.png">

## Acceptance criteria
- [x] Enemy name, initiative, HP and AC can be entered in input fields and submitted with the "add enemy button"
- [x] Form resets so additional enemy entries can be added by clicking the "add enemy" button
- [x] Player name, initiative and HP can be entered in input fields and submitted with the "add player" button
- [x] Form resets so additional player inputs can be added by clicking the "add player" button
- [x] Initiative, HP and AC inputs are only allowed to contain positive integer numbers
- [x] HP and AC inputs are only allowed to contain numbers with less than 3 digits
- [x] All inputs need to contain at least one character that isn't an empty space for the submit to work
- [x] At least one enemy and one player need to be submitted for the "Start Encounter" button to be active
- [x] Clicking the "Start Encounter" button navigates to the Encounter Page
- [x] The creature entries on the Encounter Page are displayed in order of initiative (highest to lowest)
- [x] Entries are stored in localStorage so they don't disappear on reload
- [x] Clicking the "End Encounter" button deletes the localStorage and navigates back to the Create Page

## Tasks
- [x] Create feature branch
- [x] Create CreateEnemy component in Storybook
- [x] Create CreatePlayer component in Storybook
- [x] Create CreatePage component in Storybook
- [x] Create PageButton component in Storybook
- [x] Add initiative display to EnemyEntry and PlayerEntry components
- [x] Add localStorage
- [x] Write component tests
- [x] Add components to app (feature implementation with state)
- [ ] Add missing styles
- [ ] Write integration tests w/ Cypress

## Complexity
high
