### ISSUE TITLE
HP Calculator

### ISSUE THREAD

**Issue by ninasander** [ninasander/capstone-project#3]
## Value statement
As a Game Master
I need the ability to add or subtract a number from my creature's HP
so that I can keep track of the damage or healing my creature received

## Description (Text, Scribble, Wireframe, Design)
<img width="269" alt="Bildschirmfoto 2020-08-31 um 22 07 49" src="https://user-images.githubusercontent.com/67911826/91763825-7794f180-ebd6-11ea-859d-70a30f9edcb8.png">

## Acceptance criteria
- [x] Both current and max. HP are displayed
- [x] Only a positive integer number can be entered in the input field
- [x] The "subtract" button subtracts the input value from the current HP value
- [x] The "add" button adds the input value to the current HP value
- [x] The input field resets after pressing the "add" or "subtract" button
- [x] The current HP value cannot become lower than 0 or higher than the max. HP

## Tasks
- [x] Create feature branch
- [x] Create HPCalculator component in Storybook
- [x] Update EnemyEntry component in Storybook
- [x] Write component tests
- [x] Add components to app (feature implementation with state)
- [x] Add missing styles
- [ ] Write integration tests w/ Cypress

## Complexity
high
