### ISSUE TITLE
Edit encounter

### ISSUE THREAD

**Issue by ninasander** [ninasander/capstone-project#4]
## Value statement
As a Game Master
I need a preview of already submitted entries with a delete and edit button
so that I can keep track of which entries I have added and to edit and delete them when needed

## Description (Text, Scribble, Wireframe, Design)
![image](https://user-images.githubusercontent.com/67911826/92615233-2d3dff80-f2bd-11ea-8a16-594c76e91440.png)

## Acceptance criteria
- [x] When the first entry is submitted the "Show created entries" button is displayed
- [x] Clicking the "Show created entries" button toggles the display of an entry preview
- [x] Every entry preview has a delete and edit button
- [x] Clicking the delete button deletes the entry
- [x] Clicking the edit button deletes the entry but enters the entry's values into the submit form to be edited and resubmitted

## Tasks
- [x] Create feature branch
- [x] Create EnemyPreview component in storybook
- [x] Create PlayerPreview component in storybook
- [x] Create EditButton component in storybook
- [x] Create EditPage component in storybook
- [x] Add edit and delete logic
- [x] Write component tests
- [x] Add components to app
- [x] Add missing styles
- [x] Write integration tests w/ Cypress

## Size
large
