### ISSUE TITLE
Temporary HP

### ISSUE THREAD

**Issue by ninasander** [ninasander/capstone-project#5]
## Value statement
As a Game Master
I need to see the temporary HP of my enemies and the ability to add a number to them
so that I can keep track of the temporary HP bonuses they have received in an encounter

## Description (Text, Scribble, Wireframe, Design)
<img width="523" alt="Bildschirmfoto 2020-08-28 um 17 05 00" src="https://user-images.githubusercontent.com/67911826/91582821-a306aa80-e950-11ea-858a-b761a0ebccee.png">

## Acceptance criteria
- [ ] The default display for temp. HP is "-"
- [ ] Pressing the "temp" button adds the input number to the temp. HP count
- [ ] If temp. HP exist every "subtract" input is subtracted from the temp. HP, not the current HP, until the temp. HP are back to 0
- [ ] Temp. HP cannot become negative
- [ ] Every "subtract" input exceeding the count of temp. HP needs to be split between the temp. HP and current HP (Example: Current HP: 40, Temp. HP: 10, "subtract" input: 15 -> Temp. HP: 10 -10 = 0, Current HP: 40-5 = 35)

## Tasks
- [ ] Create feature branch
- [ ] Update Counter component in storybook
- [ ] Update EnemyEntry component in storybook

## Complexity
medium
